### ISSUE TITLE
Estudo da Gestão da Potência Fornecida

### ISSUE THREAD

**Issue by ricardofalcao** [ES-FEUP-Team-B/Issues#1]

**Comment by barrosfilipe8** [comment]
- Estudo de potencia contratada (preços ao longo do dia e quantidade)
- Estudo da opção de autoconsumo 
- Previsão do consumo do condomínio (Estudo da frequência de consumo de potência por parte dos inclinos (tanto das casas em si como do nosso sistema, falar com equipa de carros para saber qual vai ser a potência consumida do nosso sistema para varios tipos de casos, baixo consumo, alto consumo, consumo médio))

**Comment by tonyfrr** [comment]
Previsao não será nesta fase
